### ISSUE TITLE
SuperBVote Nullpointer

### ISSUE THREAD

**Issue by sandor111** [minecrafter/SuperbVote#55]
Nullpointer:
`[SuperbVote] Task #1132556 for SuperbVote v0.4.1 generated an exception
java.lang.NullPointerException
	at java.lang.String.replace(String.java:2240) ~[?:1.8.0_151]
	at io.minimum.minecraft.superbvote.configuration.message.placeholder.SuperbVotePlaceholderProvider.apply(SuperbVotePlaceholderProvider.java:9) ~[SuperbVote-0.4.1.jar:?]
	at io.minimum.minecraft.superbvote.configuration.message.MessageBase.replace(MessageBase.java:19) ~[SuperbVote-0.4.1.jar:?]
	at io.minimum.minecraft.superbvote.configuration.message.PlainStringMessage.getWithOfflinePlayer(PlainStringMessage.java:33) ~[SuperbVote-0.4.1.jar:?]
	at io.minimum.minecraft.superbvote.signboard.TopPlayerSignUpdater.run(TopPlayerSignUpdater.java:60) ~[SuperbVote-0.4.1.jar:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[paper.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [paper.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [paper.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [paper.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [paper.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [paper.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]`

**Comment by astei** [comment]
Please update to SuperbVote 0.5.1, this issue is already fixed.

**Comment by sandor111** [comment]
Updated but still getting the warning:
`[SuperbVote] Task #14598 for SuperbVote v0.5.1 generated an exception
java.lang.NullPointerException
	at java.lang.String.replace(String.java:2240) ~[?:1.8.0_151]
	at io.minimum.minecraft.superbvote.configuration.message.placeholder.SuperbVotePlaceholderProvider.apply(SuperbVotePlaceholderProvider.java:9) ~[SuperbVote-0.5.1.jar:?]
	at io.minimum.minecraft.superbvote.configuration.message.MessageBase.replace(MessageBase.java:19) ~[SuperbVote-0.5.1.jar:?]
	at io.minimum.minecraft.superbvote.configuration.message.PlainStringMessage.getWithOfflinePlayer(PlainStringMessage.java:33) ~[SuperbVote-0.5.1.jar:?]
	at io.minimum.minecraft.superbvote.signboard.TopPlayerSignUpdater.run(TopPlayerSignUpdater.java:61) ~[SuperbVote-0.5.1.jar:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[paper.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [paper.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [paper.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [paper.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [paper.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [paper.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]`

**Comment by astei** [comment]
Paste your config.yml

**Comment by sandor111** [comment]
https://pastebin.com/RmSxA0t9

**Comment by astei** [comment]
That would suggest that your `usercache.json` was deleted at some point and we weren't able to lookup a corrected name.

I can implement username support for the JSON backend in 0.5.4, but as a temporary workaround you can use 0.5.2-1.12 with the MySQL backend.

**Comment by astei** [comment]
Closing since this issue can be worked around.
